version: '3.8'

services:
  amplify-astro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount for development hot-reload (comment out for production)
      # - ./src:/app/src:ro
      # - ./public:/app/public:ro
